---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: vote-ci
spec:
  pipelineRef:
    name: instavote-ci
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
  - name: dockerconfig
    secret:
      secretName: dockerhub-creds
  params:
  - name: repoUrl
    value: https://github.com/ennc0d3-learn/instavote.git
  - name: revision
    value: main
  - name: sparseCheckoutDirectories
    value: /vote/
  - name: imageUrl
    value: ennc0d3/vote
  - name: pathToContext
    value: vote

